[package]
name = "pow"
version = "0.1.0"
authors = ["lt <tabor.lukasz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
sha2 = "0.9"
num_cpus = "1.1"